### ISSUE TITLE
Test Instructions

### ISSUE THREAD

**Issue by hsuastegui** [uh-joan/firefly-test#1]
Hi Joan! We spoke on the phone about this test, can you please provide the instructions for the test? I already have it running. Thanks

**Comment by uh-joan** [comment]
Hi Humberto,

Look at the readme on the  tests branch, there are some instructions there. 
https://github.com/uh-joan/firefly-test/tree/tests

Let me know if you have any problem,
Cheets

**Comment by uh-joan** [comment]
Hey, 

Do you mean to run the e2e tests?

Excuse the brevity. Sent from J's phone.
